### ISSUE TITLE
Error 2 when installing on linux - build_libs_release

### ISSUE THREAD

**Issue by amyhouseman** [imgag/ngs-bits#269]
Hello, 

I am trying to install ngs-bits onto a linux hpc system.
I have done this so far:

clone --recursive https://github.com/imgag/ngs-bits.git
cd ngs-bits
make build_3rdparty

but neither build_libs_release or build_tools_release are working they both say similar errors: 

```
[c.c21087028@cl1 ngs-bits]$ make build_libs_release
rm -rf build-libs-Linux-Release;
mkdir -p build-libs-Linux-Release;
cd build-libs-Linux-Release; \
        qmake ../src/libs.pro "CONFIG-=debug" "CONFIG+=release" "DEFINES+=QT_NO_DEBUG_OUTPUT"; \
        make -j5;
/bin/sh: line 1: qmake: command not found
make[1]: Entering directory `/scratch/c.c21087028/Polyposis_Exome_Analysis_Novogene/ngs-bits/build-libs-Linux-Release'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory `/scratch/c.c21087028/Polyposis_Exome_Analysis_Novogene/ngs-bits/build-libs-Linux-Release'
make: *** [build_libs_release] Error 2
```

I assume i need to have qmake but I do not know how to get this?
Any suggestions?
Thanks, 
Amy

**Comment by amyhouseman** [comment]
Thanks @ubuntolog, I'm trying to install onto our HPC, I've tried installing Qt like this: 

```
git clone git://code.qt.io/qt/qt5.gitgit clone git://code.qt.io/qt/qt5.git
cd qt5/
git checkout 5.12
perl init-repository
```

but qmake still says command does not exist. I tried to do `sudo apt-get install git make g++ qt5-default libqt5xmlpatterns5-dev libqt5sql5-mysql git python python-matplotlib libbz2-dev liblzma-dev libcurl4 libcurl4-openssl-dev`

but it says apt-get not found. 

I feel a bit stuck! Sorry, thank you for your help. Amy

**Comment by ubuntolog** [comment]
If "apt-get" is not found, you are probably using some other Linux distribution. Package names may be different for different package managers. Building Qt from the source code and configuring it manually is usually a bad idea.

**Comment by amyhouseman** [comment]
hm seems that way, when i do ` uname --kernel-name --kernel-release --machine`
it says Linux 3.10.0-1160.42.2.el7.x86_64 x86_64

**Comment by ubuntolog** [comment]
Right, it seems to be CentOS. We do not officially support it. In theory everything should work, we simply do not have the resources to test it with each Linux distro. I can only advice to read the documentation for your particular Linux distribution. The following command should probably do the trick (However, I cannot verify it, since I do not have an access to CentOS machine):

`yum install qt5-qtbase-devel`

CentOS package manager should have all the necessary dependencies (the names may be slightly different). Once all the dependencies are there, you should be able to build the project. I will have to close the issue.

**Comment by amyhouseman** [comment]
Thank you! I’m also going to try the conda installation for ngs-bits

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
