### ISSUE TITLE
BedAnnotateGC bad alloc error

### ISSUE THREAD

**Issue by enBiter** [imgag/ngs-bits#392]
Hello. I'm trying to implement clinCNV in our pipeline, but I've been stuck on GC annotation step with BedAnnotateGC.
```
BedAnnotateGC 2022_12
Exception: std::bad_alloc
```
The RAM on my system never gets filled over 30 GB and I've set swappines to 10 (thus swap is not used at all while running BedAnnotateGC). I've tried running BedAnnotateGC in a provided docker container and also in a docker container where I've build ngs-bits from source.

Size of my bed file is 9.9 Gb and I use hg38 reference genome from GATK source bucket.

I realize that this error might be hard to pinpoint, so question is, can I annotate my bed files using bedtools?

Best,
Dmitry

**Comment by marc-sturm** [comment]
Hi Dmitry,

the size of the BED file is probably the problem.
When I implemented it, I did not expect 10GB.

Why is it that big?
Our BED files are 100MB max, when binning HG38 into 1000 base bins.

Best,
  Marc

**Comment by GermanDemidov** [comment]
Yes, the bed file is bigger than the human reference genome size. Something is strange here.

**Comment by enBiter** [comment]
Maybe I misunderstood the docs. The bed file was generated from bam using bedtools:
`bedtools bamtobed -i $INPUT_FILENAME > $OUTPUT_FILENAME`
Top 5 lines of my bed file:
```
chr1    9997    10054   NB501049:223:HNT73BGXB:3:23501:26627:18014/2    0       -
chr1    10003   10044   NB501049:223:HNT73BGXB:4:23501:14786:19186/1    0       +
chr1    10007   10053   NB501049:223:HNT73BGXB:2:21212:19062:9734/1     0       +
chr1    10008   10043   NB501049:223:HNT73BGXB:3:23501:26627:18014/1    0       +
chr1    10013   10047   NB501049:223:HNT73BGXB:2:23310:16770:20238/1    0       +
```
Seems like I should specify binning somewhere...

The bam file itself was produced from paired-end fastq by GATK (https://gatk.broadinstitute.org/hc/en-us/articles/360035535912-Data-pre-processing-for-variant-discovery).

**Comment by GermanDemidov** [comment]
I used this routine https://github.com/imgag/ngs-bits/issues/392#issuecomment-1431021860 . I'd increase the size of the bin - it does not make sense to run ClinCNV with such tiny bits, they will be hypervariable (or if you still want to proceed with these 40bp probes - perform analysis by each chromosome separately). We use 1KB windows, I'd say for a standard 50x WGS 500bp is also fine. You can make them overlapping, but not SO MUCH overlapping - e.g. 50% overlap is fine, but in your case it is like 90% overlap. We use non-ovelapping windows. Otherwise the coverage files get too big and such small variants are better to be found with SV callers such as Manta.

**Comment by marc-sturm** [comment]
bamtobed is not what you want.

You need to create a file with coverage information per exon (WES) or bin (typically 1000 bases for WGS) for each sample.
You can use the ngs-bits tool BedCoverage for that.

Additionally you need the file with the GC-content annotated for GC-normalization.

To do all that you need a BED file with the target region (WES) or bins (WGS).
For WGS you can use the the ngs-bits tools BedChunk to chop the WGS region into bins.
