### ISSUE TITLE
CMakeLists.txt

### ISSUE THREAD

**Issue by bioprog** [imgag/ngs-bits#7]
Hi,

I'm running on Ubuntu 16.04
The following packages are installed:
g++ 5.4.0
qt5-default 5.5.1
libqt5xmlpatterns5-dev 5.5.1
libqt5sql5-mysql 5.5.1
cmake 3.5.1

```
$ make build_3rdparty
cd bamtools && rm -rf bin build lib include src/toolkit/bamtools_version.h
mkdir bamtools/build
cd bamtools/build && cmake .. && make
CMake Error: The source directory "/home/bioinf/Software/ngs-bits-master/bamtools" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Makefile:108: recipe for target 'build_3rdparty' failed
make: *** [build_3rdparty] Error 1
```

Any ideas what went wrong here?

**Comment by marc-sturm** [comment]
I guess the bamtools folder is empty. In that case you probably have cloned
without the '--recursive' argument.

Best,
  Marc

**Comment by bioprog** [comment]
Hi Marc,
I didn't use the command from the documentation, I just clicked on the green button ("Clone or Download" -> "Download ZIP"). I'm gonna try it again now via git. Why does this make a difference btw?

**Comment by marc-sturm** [comment]
When the project includes other sub-projects, a non-recursive clone will
not clone the sub-projects.

Best, Marc

Am 26.05.2017 11:25 schrieb "bioprog" <notifications@github.com>:

Hi Marc,
I didn't use the command from the documentation, I just clicked on the
green button ("Clone or Download" -> "Download ZIP"). I'm gonna try it
again now via git. Why does this make a difference btw?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/imgag/ngs-bits/issues/7#issuecomment-304235483>, or mute
the thread

**Comment by bioprog** [comment]
During compilation there are several warnings about int / uint comparisons + set but unused variables ... but I guess you're aware of that.
But it's working now, thanks :)
