### ISSUE TITLE
Implement report for somatic single-sample

### ISSUE THREAD

**Issue by marc-sturm** [imgag/ngs-bits#88]

**Comment by marc-sturm** [comment]
Content:
- All variants after filtering (small variants)
- Coverage statistcs

**Comment by axelgschwind** [comment]
results of zoom meeting 10-09-2020 with MHH:

- Use in-house NGSD classification (at MHH) for description of variants, then somatic classification and then CGI classification for tumor onlys.

- Coverage statistics should be provided per region AND provide a value for the coverage within that region!

- The low coverage statistics should be based on 500x instead of 100x
When this is done provid

**Comment by axelgschwind** [comment]
I've pushed https://github.com/imgag/ngs-bits/commit/243979bf7280cb53e5f48d3a160b350771547b23 today. I've set it to hold because we need a feedback from MHH whether they can work with it.

**Comment by axelgschwind** [comment]
Tumor only report was approved today in video conference by MHH.
