### ISSUE TITLE
about CnvHunter

### ISSUE THREAD

**Issue by nordhuang** [imgag/ngs-bits#9]
when I run the following command 
./CnvHunter -in xxx/S003_cfdna_depth.tsv xxx/S010_gdna_depth.tsv -out xx/cnvhunter.tsv ,
i always get the following excepthion,
Exception: At least n+1 input files are required! Got 2!
Location : ../../src/CnvHunter/main.cpp:554..............Help!

**Comment by marc-sturm** [comment]
Hi, CnvHunter needs al least n (it's a parameter with default value 20)
input coverage profiles to calculate the normal distribution for each exon.
So you need more Input Files, even when you want to look at two files only.
Best, Marc

Am 05.06.2017 09:45 schrieb "nordhuang" <notifications@github.com>:

when I run the following command
./CnvHunter -in xxx/S003_cfdna_depth.tsv xxx/S010_gdna_depth.tsv -out
xx/cnvhunter.tsv ,
i always get the following excepthion,
Exception: At least n+1 input files are required! Got 2!
Location : ../../src/CnvHunter/main.cpp:554..............Help!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/imgag/ngs-bits/issues/9>, or mute the thread

**Comment by imgag** [comment]
Since there was no further feedback, I consider this issue solved.
